export const userConstants = {
  APPLICANT_LOGIN: "applicantlogin",
  APPLICANT_SIGNUP: "applicantsignup",
  APPLICANT_SIGNUP_CHECK: "applicantsignupcheck",
  APPLICANT_PROFILE_FETCH: "getapplicantprofile",
  APPLICANT_PROFILE_SUMMARY_POST: "applicantprofilesummary",
  APPLICANT_PROFILE_EXPERIENCE_POST: "applicantprofileexperience",
  APPLICANT_PROFILE_EDUCATION_POST: "applicantprofileeducation",
  APPLICANT_PROFILE_SKILLS_POST: "applicantprofileskills",
  APPLICANT_PROFILE_PHOTO_POST: "applicantprofilephoto",
  APPLICANT_PROFILE_DELETE: "applicantprofiledelete",
  MAKE_CONNECTION_REQUEST: "makeconnections",
  GET_ALL_CONNECTIONS: "getAllConnections",
  CONNECTION_RESPONSE: "connectionresponse",
  SEARCH_PEOPLE: "searchpeople",
  SAVE_JOB: "saveajob",
  APPLY_JOB: "applyjob",
  GET_SAVEDJOBS: "getsavedjobs",
  SEARCH_JOBS: "searchjob",
  UPDATE_JOB_VIEWS: "updatejobviews",
  LOG_APPLY_APPLICATION_TYPES: "logapplyapplicationtypes",
  LOG_APPLICANT_PROFILE_VIEW: "logapplicantprofileview",
  USER_DETAILS: "user_details",
  AUTH_TOKEN: "auth_token",
};
